#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-tclust
Version  : 1.5.4
Release  : 52
URL      : https://cran.r-project.org/src/contrib/tclust_1.5-4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/tclust_1.5-4.tar.gz
Summary  : Robust Trimmed Clustering
Group    : Development/Tools
License  : GPL-3.0
Requires: R-tclust-lib = %{version}-%{release}
BuildRequires : R-mclust
BuildRequires : R-mvtnorm
BuildRequires : R-sn
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# `tclust`: Robust Trimmed Clustering
<!-- badges: start -->
[![CRAN
version](https://www.r-pkg.org/badges/version/tclust)](https://cran.r-project.org/package=tclust)
[![R-CMD-check](https://github.com/valentint/tclust/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/valentint/tclust/actions/workflows/R-CMD-check.yaml)
[![downloads](https://cranlogs.r-pkg.org/badges/tclust)](https://cran.r-project.org/package=tclust)
[![downloads](https://cranlogs.r-pkg.org/badges/grand-total/tclust)](https://cran.r-project.org/package=tclust)
[![license](https://img.shields.io/badge/license-GPL--3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0.en.html)

%package lib
Summary: lib components for the R-tclust package.
Group: Libraries

%description lib
lib components for the R-tclust package.


%prep
%setup -q -n tclust

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1679689986

%install
export SOURCE_DATE_EPOCH=1679689986
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/tclust/CITATION
/usr/lib64/R/library/tclust/DESCRIPTION
/usr/lib64/R/library/tclust/INDEX
/usr/lib64/R/library/tclust/Meta/Rd.rds
/usr/lib64/R/library/tclust/Meta/data.rds
/usr/lib64/R/library/tclust/Meta/features.rds
/usr/lib64/R/library/tclust/Meta/hsearch.rds
/usr/lib64/R/library/tclust/Meta/links.rds
/usr/lib64/R/library/tclust/Meta/nsInfo.rds
/usr/lib64/R/library/tclust/Meta/package.rds
/usr/lib64/R/library/tclust/Meta/vignette.rds
/usr/lib64/R/library/tclust/NAMESPACE
/usr/lib64/R/library/tclust/R/tclust
/usr/lib64/R/library/tclust/R/tclust.rdb
/usr/lib64/R/library/tclust/R/tclust.rdx
/usr/lib64/R/library/tclust/data/M5data.rda
/usr/lib64/R/library/tclust/data/geyser2.rda
/usr/lib64/R/library/tclust/data/swissbank.rda
/usr/lib64/R/library/tclust/doc/index.html
/usr/lib64/R/library/tclust/doc/tclust.R
/usr/lib64/R/library/tclust/doc/tclust.pdf
/usr/lib64/R/library/tclust/doc/tclust.rnw
/usr/lib64/R/library/tclust/help/AnIndex
/usr/lib64/R/library/tclust/help/aliases.rds
/usr/lib64/R/library/tclust/help/paths.rds
/usr/lib64/R/library/tclust/help/tclust.rdb
/usr/lib64/R/library/tclust/help/tclust.rdx
/usr/lib64/R/library/tclust/html/00Index.html
/usr/lib64/R/library/tclust/html/R.css
/usr/lib64/R/library/tclust/tests/ttclust.R
/usr/lib64/R/library/tclust/tests/ttclust.Rout.save
/usr/lib64/R/library/tclust/work/clust.cpp
/usr/lib64/R/library/tclust/work/clust.h
/usr/lib64/R/library/tclust/work/tclust-notes.txt

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/tclust/libs/tclust.so
/usr/lib64/R/library/tclust/libs/tclust.so.avx2
/usr/lib64/R/library/tclust/libs/tclust.so.avx512
